### ISSUE TITLE
CircuitBreaker, Timelimiter patterns for the interceptor

### ISSUE THREAD

**Issue by KafkaProServerless** [making/retryable-client-http-request-interceptor#22]
Hello,

I am here after watching Dan Vega's videos on Rest Client.

From there, we are using your project, and liking it a lot.

With that said, we would like to also set CircuitBreaker and TimeLimiter patterns as well.

Would it be possible to add those in the interceptor please?

Thank you

**Comment by making** [comment]
Thanks for the feedback.

This interceptor focuses only on retrying.
Circuit breaker may be implemented as separate interceptor (separate project).
Regarding the time limiter, I think it is best to use the timeout setting at the HTTP client level.

**Comment by making** [comment]
Although off topic for this issue, I introduced a mechanism for client-side load balancing as it needs to be done during retry.

https://github.com/making/retryable-client-http-request-interceptor/pull/24
